### ISSUE TITLE
schematic and footprint

### ISSUE THREAD

**Issue by dennisleexyz** [saoto28/pineapple60#1]
I saw you uploaded PDFs from KiCad. Will you be uploading the source files too?

You inspired me to work on a very similar project, so I am interested to use the Kailh X switch PCB footprint and see how the trackpoint connection is made. Thanks :)

**Comment by saoto28** [comment]
Though I'm not confident with my cad data, I put my KiCad data on the repository for just reference. 
Maybe there is some missing data. Please point out.

**Comment by dennisleexyz** [comment]
I was able to export footprints from your PCB for external use.

I looked up the switch footprint and found issue by you (shikamiya/kicad-footprint-kailh-pg1425-x-switch#2). Is it fixed in your PCB?

**Comment by saoto28** [comment]
Yes, it is.
The attachment is a part of my first PCB drawing.
A and B are the pin points of Kailh x switch. But, the x switch has two steel points bottom besides of the pin points. And the steel points are connecting to pin A in the switch. The steel points may touch the C port of the PCB. Then the A pin and B pin may always connected.
So, I removed the D connection on my second PCB. When you use MX or ALPS switch, you have to connect the D.
![image](https://user-images.githubusercontent.com/33110199/106733053-c1d24100-6654-11eb-8f50-9f772b73dc26.png)
And, the hole sizes for Kailh switches were not correct. I will correct them.

**Comment by saoto28** [comment]
I've uploaded a footprint that was corrected about the pad's size for the choc and x-switch.
https://github.com/saoto28/pineapple60/tree/main/KiCad/kailh-pg1425-x-switch.pretty

**Comment by saoto28** [comment]
I found a bad point in the footprint. The corner curvature of the square hole for the X-switch was too big. Some X-switch is not inserted smoothly. I'll make the curvature small.

**Comment by saoto28** [comment]
The CAD drawing was no problem. The curvature is 0.25 radius. It looks small enough. So, it was just a manufacturing issue of JLCPCB.
